name: nlp_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  - jupyter
  - pip
  - pip:
      - gensim
      - spacy
      - nltk
      - ipykernel
      - tensorflow
      - torch
      - torchvision
      - torchaudio
